/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalRole;

import Buisness.Products.Product;
import Buisness.Products.ProductDirectory;
import Business.CustomerAccount.CustomerAccount;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.Network.Network;
import Business.Order.Order;
import Business.Order.OrderDirectory;
import Business.Organization.Organization;
import Business.Organization.SupplierProcurementOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import userinterface.CartJPanel;
import userinterface.LabRole.ProductDescJPanel;
import userinterface.OrderPlacement.CustomerAccountJPanel;
import userinterface.OrderPlacement.OrderJPanel;
import userinterface.SuppliesManagerRole.Renderer1;
import userinterface.SuppliesManagerRole.ViewPanel;

/**
 *
 * @author Harshitha
 */
public class HospitalWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalWorkAreaJPanel
     */
    private CustomerAccount account;
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Organization organization;
    private Enterprise enterprise;
    public HospitalWorkAreaJPanel(JPanel userProcessContainer, CustomerAccount account, Organization organization, Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.account =account;
        this.userProcessContainer =userProcessContainer;
        this.system= system;
        this.enterprise = enterprise;
        this.organization=organization;
        mostbought();
        refreshTable();
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
         headerRenderer.setBackground(new Color(85,79,102));

         for (int i = 0; i < analyzerTable2.getModel().getColumnCount(); i++) {
        analyzerTable2.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
         for (int i = 0; i < analyzerTable3.getModel().getColumnCount(); i++) {
        analyzerTable3.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
         for (int i = 0; i < analyzerTable4.getModel().getColumnCount(); i++) {
        analyzerTable4.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        TabPanel.setBackgroundAt(0, Color.yellow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Panel = new javax.swing.JPanel();
        TabPanel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Product1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Product2 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        description1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sortbyJComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        analyzerSearch = new javax.swing.JTextField();
        incubatorTable = new javax.swing.JScrollPane();
        analyzerTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sortbyJComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        analyzerSearch1 = new javax.swing.JTextField();
        incubatorTable1 = new javax.swing.JScrollPane();
        analyzerTable3 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sortbyJComboBox2 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        analyzerSearch2 = new javax.swing.JTextField();
        incubatorTable2 = new javax.swing.JScrollPane();
        analyzerTable4 = new javax.swing.JTable();

        setBackground(new java.awt.Color(44, 44, 91));

        jButton9.setBackground(new java.awt.Color(44, 44, 91));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(171, 238, 255));
        jButton9.setText("HOME ");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(44, 44, 91));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(171, 238, 255));
        jButton10.setText("ORDERS");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(44, 44, 91));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(171, 238, 255));
        jButton11.setText("ACCOUNT");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(44, 44, 91));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(171, 238, 255));
        jButton8.setText("CART");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        Panel.setLayout(new java.awt.CardLayout());

        TabPanel.setBackground(new java.awt.Color(51, 0, 102));
        TabPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        TabPanel.setForeground(new java.awt.Color(171, 238, 255));
        TabPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabPanelMouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(44, 44, 91));
        jPanel8.setForeground(new java.awt.Color(171, 238, 255));

        jPanel9.setBackground(new java.awt.Color(44, 44, 91));

        jButton1.setBackground(new java.awt.Color(44, 44, 91));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(171, 238, 255));
        jButton1.setText("SHOP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        name.setBackground(new java.awt.Color(0, 102, 102));
        name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(171, 238, 255));

        description.setBackground(new java.awt.Color(44, 44, 91));
        description.setColumns(20);
        description.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        description.setForeground(new java.awt.Color(171, 238, 255));
        description.setRows(5);
        jScrollPane7.setViewportView(description);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Product1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78)
                .addComponent(jButton1)
                .addGap(62, 62, 62))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addGap(31, 31, 31))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Product1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(171, 238, 255));
        jLabel13.setText("BEST PRODUCTS ");

        jPanel10.setBackground(new java.awt.Color(44, 44, 91));

        jButton2.setBackground(new java.awt.Color(44, 44, 91));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(171, 238, 255));
        jButton2.setText("SHOP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        name1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        name1.setForeground(new java.awt.Color(171, 238, 255));

        description1.setBackground(new java.awt.Color(44, 44, 91));
        description1.setColumns(20);
        description1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        description1.setForeground(new java.awt.Color(171, 238, 255));
        description1.setRows(5);
        jScrollPane8.setViewportView(description1);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Product2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane8))
                .addGap(76, 76, 76)
                .addComponent(jButton2)
                .addGap(62, 62, 62))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(name1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap(65, Short.MAX_VALUE)
                        .addComponent(Product2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1111, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabPanel.addTab("HOME", jPanel2);

        jPanel3.setBackground(new java.awt.Color(44, 44, 91));
        jPanel3.setForeground(new java.awt.Color(171, 238, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(171, 238, 255));
        jLabel1.setText("SORT BY");

        sortbyJComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sortbyJComboBox.setForeground(new java.awt.Color(171, 238, 255));
        sortbyJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT AN OPTION", "PRICE LOW TO HIGH", "PRICE HIGH TO LOW" }));
        sortbyJComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortbyJComboBoxMouseClicked(evt);
            }
        });
        sortbyJComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sortbyJComboBoxItemStateChanged(evt);
            }
        });
        sortbyJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortbyJComboBoxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(171, 238, 255));
        jLabel7.setText("SEARCH");

        analyzerSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        analyzerSearch.setForeground(new java.awt.Color(171, 238, 255));
        analyzerSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                analyzerSearchKeyReleased(evt);
            }
        });

        incubatorTable.setBackground(new java.awt.Color(44, 44, 91));
        incubatorTable.setForeground(new java.awt.Color(171, 238, 255));
        incubatorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incubatorTableMouseClicked(evt);
            }
        });

        analyzerTable2.setBackground(new java.awt.Color(44, 44, 91));
        analyzerTable2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        analyzerTable2.setForeground(new java.awt.Color(171, 238, 255));
        analyzerTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "PRODUCT", "PRICE"
            }
        ));
        analyzerTable2.setRowHeight(150);
        analyzerTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                analyzerTable2MouseClicked(evt);
            }
        });
        incubatorTable.setViewportView(analyzerTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(sortbyJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(analyzerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
            .addComponent(incubatorTable)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sortbyJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(analyzerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(incubatorTable, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE))
        );

        TabPanel.addTab("DRUGS", jPanel3);

        jPanel4.setBackground(new java.awt.Color(44, 44, 91));
        jPanel4.setForeground(new java.awt.Color(171, 238, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(171, 238, 255));
        jLabel2.setText("SORT BY");

        sortbyJComboBox1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sortbyJComboBox1.setForeground(new java.awt.Color(171, 238, 255));
        sortbyJComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT AN OPTION", "PRICE LOW TO HIGH", "PRICE HIGH TO LOW" }));
        sortbyJComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortbyJComboBox1MouseClicked(evt);
            }
        });
        sortbyJComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sortbyJComboBox1ItemStateChanged(evt);
            }
        });
        sortbyJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortbyJComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(171, 238, 255));
        jLabel8.setText("SEARCH");

        analyzerSearch1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        analyzerSearch1.setForeground(new java.awt.Color(171, 238, 255));
        analyzerSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzerSearch1ActionPerformed(evt);
            }
        });
        analyzerSearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                analyzerSearch1KeyReleased(evt);
            }
        });

        incubatorTable1.setBackground(new java.awt.Color(44, 44, 91));
        incubatorTable1.setForeground(new java.awt.Color(171, 238, 255));
        incubatorTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        incubatorTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incubatorTable1MouseClicked(evt);
            }
        });

        analyzerTable3.setBackground(new java.awt.Color(44, 44, 91));
        analyzerTable3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        analyzerTable3.setForeground(new java.awt.Color(171, 238, 255));
        analyzerTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "PRODUCT", "PRICE"
            }
        ));
        analyzerTable3.setRowHeight(150);
        analyzerTable3.setSelectionBackground(new java.awt.Color(85, 79, 102));
        analyzerTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                analyzerTable3MouseClicked(evt);
            }
        });
        incubatorTable1.setViewportView(analyzerTable3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(sortbyJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(analyzerSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
            .addComponent(incubatorTable1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sortbyJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(analyzerSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(incubatorTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE))
        );

        TabPanel.addTab("VACCINES", jPanel4);

        jPanel5.setBackground(new java.awt.Color(44, 44, 91));
        jPanel5.setForeground(new java.awt.Color(171, 238, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(171, 238, 255));
        jLabel3.setText("SORT BY");

        sortbyJComboBox2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sortbyJComboBox2.setForeground(new java.awt.Color(171, 238, 255));
        sortbyJComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT AN OPTION", "PRICE LOW TO HIGH", "PRICE HIGH TO LOW" }));
        sortbyJComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortbyJComboBox2MouseClicked(evt);
            }
        });
        sortbyJComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sortbyJComboBox2ItemStateChanged(evt);
            }
        });
        sortbyJComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortbyJComboBox2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(171, 238, 255));
        jLabel9.setText("SEARCH");

        analyzerSearch2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        analyzerSearch2.setForeground(new java.awt.Color(171, 238, 255));
        analyzerSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzerSearch2ActionPerformed(evt);
            }
        });
        analyzerSearch2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                analyzerSearch2KeyReleased(evt);
            }
        });

        incubatorTable2.setBackground(new java.awt.Color(44, 44, 91));
        incubatorTable2.setForeground(new java.awt.Color(171, 238, 255));
        incubatorTable2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        incubatorTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incubatorTable2MouseClicked(evt);
            }
        });

        analyzerTable4.setBackground(new java.awt.Color(44, 44, 91));
        analyzerTable4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        analyzerTable4.setForeground(new java.awt.Color(171, 238, 255));
        analyzerTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "PRODUCT", "PRICE"
            }
        ));
        analyzerTable4.setRowHeight(150);
        analyzerTable4.setSelectionBackground(new java.awt.Color(85, 79, 102));
        analyzerTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                analyzerTable4MouseClicked(evt);
            }
        });
        incubatorTable2.setViewportView(analyzerTable4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(sortbyJComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(analyzerSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
            .addComponent(incubatorTable2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sortbyJComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(analyzerSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incubatorTable2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE))
        );

        TabPanel.addTab("EQUIPMENTS", jPanel5);

        Panel.add(TabPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(30, 30, 30)
                .addComponent(jButton10)
                .addGap(28, 28, 28)
                .addComponent(jButton11)
                .addGap(26, 26, 26)
                .addComponent(jButton8)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton10, jButton11, jButton8, jButton9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton10, jButton11, jButton8, jButton9});

    }// </editor-fold>//GEN-END:initComponents
    public void  mostbought(){
        OrderDirectory od = new OrderDirectory();
        ProductDirectory prod = new ProductDirectory();
    Map<Integer,Integer> mostbought =  new HashMap<Integer,Integer>();
    for(CustomerAccount account1 : organization.getCustomerAccountDirectory().getUserAccountList()){
            for(Order o : account1.getOrderDirectory().getOrderList()){
                od.getOrderList().add(o);
            }
        }
    for (Order o : od.getOrderList()){
        for(Product p : o.getProductList()){
           prod.getAllProducts().add(p);
        }
    }
    for (Product p : prod.getAllProducts()){
        int noofQuantity = p.getQuantity();
        int noofproducts =0;
        for(int i= noofQuantity;i>0;i--){
        if(mostbought.containsKey(p.getID()))
            noofproducts = mostbought.get(p.getID());
        noofproducts+=1;
        noofQuantity = noofQuantity -1;
        mostbought.put(p.getID(),noofproducts);
        }
    }
    Set<Map.Entry<Integer,Integer>> set = mostbought.entrySet();
    List<Map.Entry<Integer,Integer>> list = new ArrayList<Map.Entry<Integer,Integer>>(set);
    Collections.sort(list,new Comparator<Map.Entry<Integer,Integer>>()
    {
        public int compare(Map.Entry<Integer,Integer> o1,Map.Entry<Integer,Integer> o2){
            return(o2.getValue()).compareTo(o1.getValue());
        }
    });
    int productID = 0 ;
    System.out.println("\n Top most bought products");
    for(int i =0; i< list.size() && i< 1 ;i++){
        System.out.println(list.get(i));
        productID = list.get(i).getKey();
    }
   for(Product p : prod.getAllProducts()){
       if(productID == p.getID()){
           name.setText(p.getName());
           description.setText(p.getDesc());
           BufferedImage imgFromDb = null;
        InputStream in = new ByteArrayInputStream(p.getImagetry());
        try {
             imgFromDb = ImageIO.read(in);
             ImageIcon icon = new ImageIcon(imgFromDb);
//    ImageIcon i = ResizeImage(imgFromDb,null);
        Product1 .setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(ViewPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
   } 
   int productID2 = 0;
   for(int i =0; i< list.size() && i< 2 ;i++){
        System.out.println(list.get(i));
        productID2 = list.get(i).getKey();
    }
   for(Product p : prod.getAllProducts()){
       if(productID2 == p.getID()){
           name1.setText(p.getName());
           description1.setText(p.getDesc());
           BufferedImage imgFromDb = null;
        InputStream in = new ByteArrayInputStream(p.getImagetry());
        try {
             imgFromDb = ImageIO.read(in);
             ImageIcon icon = new ImageIcon(imgFromDb);
//    ImageIcon i = ResizeImage(imgFromDb,null);
        Product2 .setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(ViewPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
   } 
 }
    
    public void refreshTable(){
        int rowCount1 = analyzerTable2.getRowCount();
            DefaultTableModel model1 = (DefaultTableModel)analyzerTable2.getModel();
        for(int i = rowCount1 - 1; i >=0; i--) {
            model1.removeRow(i);
        }
        for(Network network:system.getNetworkList()){
            for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof SupplierEnterprise){
                        for(Organization o :e.getOrganizationDirectory().getOrganizationList()){
                        if(o instanceof SupplierProcurementOrganization){
                                for(Product p :o.getProductDirectory().getDrugproductlist()){
//                                        Object row[] = new Object[3];
//                                        row[0] =p; 
//                                        row[1]=p.getImagetry();
//                                        row[2]=p.getPrice();
//                                        model1.addRow(row);
                                   Product pro=p;
            
            double price=p.getPrice();
            
            
             BufferedImage imgFromDb = null;
        InputStream in = new ByteArrayInputStream(p.getImagetry());
        try {
             imgFromDb = ImageIO.read(in);
               
    ImageIcon icon = new ImageIcon(imgFromDb);
         //img.setIcon(icon);
//         Renderer1 re= new Renderer1();
//            re.lbl.setIcon(icon);
//            tblDirectory.getColumnModel().getColumn(3).setCellRenderer(re);
    
    model1.addRow(new Object[] {pro,p.getImagetry(),price});
    analyzerTable2.getColumnModel().getColumn(1).setCellRenderer(new Renderer1());
    
        } catch (IOException ex) {
            Logger.getLogger(ViewPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
                                    }
                                }
                            }
                        }
                    }    
          int rowCount2 = analyzerTable3.getRowCount();
            DefaultTableModel model2 = (DefaultTableModel)analyzerTable3.getModel();
        for(int i = rowCount2 - 1; i >=0; i--) {
            model2.removeRow(i);
        }
        for(Network network:system.getNetworkList()){
            for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof SupplierEnterprise){
                        for(Organization o :e.getOrganizationDirectory().getOrganizationList()){
                        if(o instanceof SupplierProcurementOrganization){
                                for(Product p :o.getProductDirectory().getVaccineproductlist()){
                                        Product pro=p;
            
            double price=p.getPrice();
            
            
             BufferedImage imgFromDb = null;
        InputStream in = new ByteArrayInputStream(p.getImagetry());
        try {
             imgFromDb = ImageIO.read(in);
               
    ImageIcon icon = new ImageIcon(imgFromDb);
         //img.setIcon(icon);
//         Renderer1 re= new Renderer1();
//            re.lbl.setIcon(icon);
//            tblDirectory.getColumnModel().getColumn(3).setCellRenderer(re);
    
    model2.addRow(new Object[] {pro,p.getImagetry(),price});
    analyzerTable3.getColumnModel().getColumn(1).setCellRenderer(new Renderer1());
    
        } catch (IOException ex) {
            Logger.getLogger(ViewPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
                                    }
                                }
                            }
                        }
                    }    
        int rowCount3 = analyzerTable4.getRowCount();
            DefaultTableModel model3 = (DefaultTableModel)analyzerTable4.getModel();
        for(int i = rowCount3 - 1; i >=0; i--) {
//            model2.removeRow(i);
        }
        for(Network network:system.getNetworkList()){
            for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof SupplierEnterprise){
                        for(Organization o :e.getOrganizationDirectory().getOrganizationList()){
                        if(o instanceof SupplierProcurementOrganization){
                                for(Product p :o.getProductDirectory().getEquipproductlist()){
                                                      Product pro=p;
            
            double price=p.getPrice();
            
            
             BufferedImage imgFromDb = null;
        InputStream in = new ByteArrayInputStream(p.getImagetry());
        try {
             imgFromDb = ImageIO.read(in);
               
    ImageIcon icon = new ImageIcon(imgFromDb);
         //img.setIcon(icon);
//         Renderer1 re= new Renderer1();
//            re.lbl.setIcon(icon);
//            tblDirectory.getColumnModel().getColumn(3).setCellRenderer(re);
    
    model3.addRow(new Object[] {pro,p.getImagetry(),price});
    analyzerTable4.getColumnModel().getColumn(1).setCellRenderer(new Renderer1());
    
        } catch (IOException ex) {
            Logger.getLogger(ViewPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
                                }
                            }
                        }
                    }    
                }
    }
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Panel.removeAll();
        Panel.add("TabPanel",TabPanel);
        CardLayout layout =(CardLayout) Panel.getLayout();
        layout.next(Panel);
        Component[] components= userProcessContainer.getComponents();
        for (Component c: components)
        {

            if(c instanceof HospitalWorkAreaJPanel)

            {
                HospitalWorkAreaJPanel panel=(HospitalWorkAreaJPanel)c;
                panel.refreshTable();
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Panel.removeAll();
        OrderJPanel order = new OrderJPanel(Panel,system,account,organization);
        Panel.add(order);
        CardLayout layout =(CardLayout) Panel.getLayout();
        layout.next(Panel);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Panel.removeAll();
        CustomerAccountJPanel customer = new CustomerAccountJPanel(Panel,system,account,organization);
        Panel.add(customer);
        CardLayout layout =(CardLayout) Panel.getLayout();
        layout.next(Panel);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Panel.removeAll();
        CartJPanel cart = new CartJPanel(Panel,system,account,organization,enterprise);
        Panel.add("Cart",cart);
        CardLayout crdLyt = (CardLayout) Panel.getLayout();
        crdLyt.next(Panel);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Product product = null;
        OrderDirectory od = new OrderDirectory();
        ProductDirectory prod = new ProductDirectory();
        for(CustomerAccount account1 : organization.getCustomerAccountDirectory().getUserAccountList()){
            for(Order o : account1.getOrderDirectory().getOrderList()){
                od.getOrderList().add(o);
            }
        }
        for (Order o : od.getOrderList()){
            for(Product p : o.getProductList()){
                prod.getAllProducts().add(p);
            }
        }
        for (Product p : prod.getAllProducts()){
            if  (name.getText().equals(p.getName()));
            product =p;
        }
        ProductDescJPanel ProductDesc= new ProductDescJPanel(Panel,product,organization,enterprise,account);
        Panel.add("ProductDesc",ProductDesc);
        CardLayout layout=(CardLayout) Panel.getLayout();
        layout.next(Panel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Product product = null;
        OrderDirectory od = new OrderDirectory();
        ProductDirectory prod = new ProductDirectory();
        for(CustomerAccount account1 : organization.getCustomerAccountDirectory().getUserAccountList()){
            for(Order o : account1.getOrderDirectory().getOrderList()){
                od.getOrderList().add(o);
            }
        }
        for (Order o : od.getOrderList()){
            for(Product p : o.getProductList()){
                prod.getAllProducts().add(p);
            }
        }
        for (Product p : prod.getAllProducts()){
            if  (name1.getText().equals(p.getName()));
            product =p;
        }
        ProductDescJPanel ProductDesc= new ProductDescJPanel(Panel,product,organization,enterprise,account);
        Panel.add("ProductDesc",ProductDesc);
        CardLayout layout=(CardLayout) Panel.getLayout();
        layout.next(Panel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sortbyJComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortbyJComboBoxMouseClicked
        if (sortbyJComboBox.getSelectedItem() == "PRICE LOW TO HIGH"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(analyzerTable2.getModel());
            analyzerTable2.setRowSorter(sorter);

            List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>(25);
            sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
        }
        else if (sortbyJComboBox.getSelectedItem() == "PRICE HIGH TO LOW"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(analyzerTable2.getModel());
            analyzerTable2.setRowSorter(sorter);

            List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>(25);
            sortKeys.add(new RowSorter.SortKey(2, SortOrder.DESCENDING));
            sorter.setSortKeys(sortKeys);
        }
    }//GEN-LAST:event_sortbyJComboBoxMouseClicked

    private void sortbyJComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sortbyJComboBoxItemStateChanged
        if (sortbyJComboBox.getSelectedItem() == "PRICE LOW TO HIGH"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(analyzerTable2.getModel());
            analyzerTable2.setRowSorter(sorter);

            List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>(25);
            sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
        }
        else if (sortbyJComboBox.getSelectedItem() == "PRICE HIGH TO LOW"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(analyzerTable2.getModel());
            analyzerTable2.setRowSorter(sorter);

            List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>(25);
            sortKeys.add(new RowSorter.SortKey(2, SortOrder.DESCENDING));
            sorter.setSortKeys(sortKeys);
        }
    }//GEN-LAST:event_sortbyJComboBoxItemStateChanged

    private void sortbyJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortbyJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortbyJComboBoxActionPerformed

    private void analyzerSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_analyzerSearchKeyReleased
        DefaultTableModel dtm = (DefaultTableModel)analyzerTable2.getModel();
        String search = analyzerSearch.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dtm);
        analyzerTable2.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_analyzerSearchKeyReleased

    private void analyzerTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analyzerTable2MouseClicked
        int selectRow= analyzerTable2.getSelectedRow();
        Product p=(Product)analyzerTable2.getValueAt(selectRow, 0);

        ProductDescJPanel ProductDesc= new ProductDescJPanel(Panel,p,organization,enterprise,account);
        Panel.add("ProductDesc",ProductDesc);
        CardLayout layout=(CardLayout) Panel.getLayout();
        layout.next(Panel);
    }//GEN-LAST:event_analyzerTable2MouseClicked

    private void incubatorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incubatorTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_incubatorTableMouseClicked

    private void sortbyJComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortbyJComboBox1MouseClicked
        if (sortbyJComboBox1.getSelectedItem() == "PRICE LOW TO HIGH"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(analyzerTable3.getModel());
            analyzerTable3.setRowSorter(sorter);

            List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>(25);
            sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
        }
        else if (sortbyJComboBox1.getSelectedItem() == "PRICE HIGH TO LOW"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(analyzerTable3.getModel());
            analyzerTable3.setRowSorter(sorter);

            List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>(25);
            sortKeys.add(new RowSorter.SortKey(2, SortOrder.DESCENDING));
            sorter.setSortKeys(sortKeys);
        }
    }//GEN-LAST:event_sortbyJComboBox1MouseClicked

    private void sortbyJComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sortbyJComboBox1ItemStateChanged
        if (sortbyJComboBox1.getSelectedItem() == "PRICE LOW TO HIGH"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(analyzerTable3.getModel());
            analyzerTable3.setRowSorter(sorter);

            List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>(25);
            sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
        }
        else if (sortbyJComboBox1.getSelectedItem() == "PRICE HIGH TO LOW"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(analyzerTable3.getModel());
            analyzerTable3.setRowSorter(sorter);

            List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>(25);
            sortKeys.add(new RowSorter.SortKey(2, SortOrder.DESCENDING));
            sorter.setSortKeys(sortKeys);
        }
    }//GEN-LAST:event_sortbyJComboBox1ItemStateChanged

    private void sortbyJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortbyJComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortbyJComboBox1ActionPerformed

    private void analyzerSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzerSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_analyzerSearch1ActionPerformed

    private void analyzerSearch1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_analyzerSearch1KeyReleased
        DefaultTableModel dtm = (DefaultTableModel)analyzerTable3.getModel();
        String search = analyzerSearch1.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dtm);
        analyzerTable3.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_analyzerSearch1KeyReleased

    private void analyzerTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analyzerTable3MouseClicked
      int selectRow= analyzerTable3.getSelectedRow();
        Product p=(Product)analyzerTable3.getValueAt(selectRow, 0);

        ProductDescJPanel ProductDesc= new ProductDescJPanel(Panel,p,organization,enterprise,account);
        Panel.add("ProductDesc",ProductDesc);
        CardLayout layout=(CardLayout) Panel.getLayout();
        layout.next(Panel);
    }//GEN-LAST:event_analyzerTable3MouseClicked

    private void incubatorTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incubatorTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_incubatorTable1MouseClicked

    private void sortbyJComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortbyJComboBox2MouseClicked
        if (sortbyJComboBox2.getSelectedItem() == "PRICE LOW TO HIGH"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(analyzerTable4.getModel());
            analyzerTable4.setRowSorter(sorter);

            List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>(25);
            sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
        }
        else if (sortbyJComboBox2.getSelectedItem() == "PRICE HIGH TO LOW"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(analyzerTable4.getModel());
            analyzerTable4.setRowSorter(sorter);

            List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>(25);
            sortKeys.add(new RowSorter.SortKey(2, SortOrder.DESCENDING));
            sorter.setSortKeys(sortKeys);
        }
    }//GEN-LAST:event_sortbyJComboBox2MouseClicked

    private void sortbyJComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sortbyJComboBox2ItemStateChanged
        if (sortbyJComboBox2.getSelectedItem() == "PRICE LOW TO HIGH"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(analyzerTable4.getModel());
            analyzerTable4.setRowSorter(sorter);

            List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>(25);
            sortKeys.add(new RowSorter.SortKey(2, SortOrder.ASCENDING));
            sorter.setSortKeys(sortKeys);
        }
        else if (sortbyJComboBox2.getSelectedItem() == "PRICE HIGH TO LOW"){
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(analyzerTable4.getModel());
            analyzerTable4.setRowSorter(sorter);

            List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>(25);
            sortKeys.add(new RowSorter.SortKey(2, SortOrder.DESCENDING));
            sorter.setSortKeys(sortKeys);
        }
    }//GEN-LAST:event_sortbyJComboBox2ItemStateChanged

    private void sortbyJComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortbyJComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortbyJComboBox2ActionPerformed

    private void analyzerSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzerSearch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_analyzerSearch2ActionPerformed

    private void analyzerSearch2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_analyzerSearch2KeyReleased
        DefaultTableModel dtm = (DefaultTableModel)analyzerTable4.getModel();
        String search = analyzerSearch2.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dtm);
        analyzerTable4.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_analyzerSearch2KeyReleased

    private void analyzerTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analyzerTable4MouseClicked
          int selectRow= analyzerTable4.getSelectedRow();
        Product p=(Product)analyzerTable4.getValueAt(selectRow, 0);

        ProductDescJPanel ProductDesc= new ProductDescJPanel(Panel,p,organization,enterprise,account);
        Panel.add("ProductDesc",ProductDesc);
        CardLayout layout=(CardLayout) Panel.getLayout();
        layout.next(Panel);
    }//GEN-LAST:event_analyzerTable4MouseClicked

    private void incubatorTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incubatorTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_incubatorTable2MouseClicked

    private void TabPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPanelMouseClicked
       refreshTable();
       mostbought();
    }//GEN-LAST:event_TabPanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel Product1;
    private javax.swing.JLabel Product2;
    private javax.swing.JTabbedPane TabPanel;
    private javax.swing.JTextField analyzerSearch;
    private javax.swing.JTextField analyzerSearch1;
    private javax.swing.JTextField analyzerSearch2;
    private javax.swing.JTable analyzerTable2;
    private javax.swing.JTable analyzerTable3;
    private javax.swing.JTable analyzerTable4;
    private javax.swing.JTextArea description;
    private javax.swing.JTextArea description1;
    private javax.swing.JScrollPane incubatorTable;
    private javax.swing.JScrollPane incubatorTable1;
    private javax.swing.JScrollPane incubatorTable2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JComboBox sortbyJComboBox;
    private javax.swing.JComboBox sortbyJComboBox1;
    private javax.swing.JComboBox sortbyJComboBox2;
    // End of variables declaration//GEN-END:variables
}
