/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Registeration;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CustomerServiceOrganization;
import Business.Organization.Organization;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author vaniv
 */
public class CustomerRegisterationJPanel extends javax.swing.JPanel {

   
    private EcoSystem system;
    private JPanel container;
    private ImageIcon i;
      String imgPath = null;
     private BufferedImage origImage;
    private byte[] immAsBytes;
    public CustomerRegisterationJPanel(JPanel container,EcoSystem system) {
        initComponents();
        this.system = system;
        this.container = container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        EmailId = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        street = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        zipcode = new javax.swing.JTextField();
        license = new javax.swing.JLabel();
        Browse = new javax.swing.JButton();
        register = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        RoleJComboBox = new javax.swing.JComboBox();
        email = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(44, 44, 91));
        jPanel1.setForeground(new java.awt.Color(171, 238, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(171, 238, 255));
        jLabel2.setText("FIRST NAME");

        firstname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(171, 238, 255));
        jLabel3.setText("LAST NAME ");

        lastname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(171, 238, 255));
        jLabel5.setText("CONTACT");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(171, 238, 255));
        jLabel6.setText("ZIPCODE");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(171, 238, 255));
        jLabel8.setText("STREET");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(171, 238, 255));
        jLabel9.setText("CITY");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(171, 238, 255));
        jLabel11.setText("LICENSE");

        EmailId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailIdActionPerformed(evt);
            }
        });
        EmailId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailIdKeyReleased(evt);
            }
        });

        contact.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        street.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetActionPerformed(evt);
            }
        });

        city.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        zipcode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Browse.setBackground(new java.awt.Color(44, 44, 91));
        Browse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Browse.setForeground(new java.awt.Color(171, 238, 255));
        Browse.setText("BROWSE");
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });

        register.setBackground(new java.awt.Color(44, 44, 91));
        register.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        register.setForeground(new java.awt.Color(171, 238, 255));
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(171, 238, 255));
        jLabel12.setText("EMAIL ID");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(171, 238, 255));
        jLabel13.setText("ROLE");

        RoleJComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RoleJComboBox.setForeground(new java.awt.Color(171, 238, 255));
        RoleJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select A Role", "Hospital", "Laboratory", "Clinic", "Pharmacy", " " }));

        email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(171, 238, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel10))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 394, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(Browse))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RoleJComboBox, 0, 210, Short.MAX_VALUE)
                                    .addComponent(firstname)
                                    .addComponent(lastname)
                                    .addComponent(EmailId, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(contact, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(city, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(street)
                                    .addComponent(zipcode))))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(register)
                                .addGap(187, 187, 187))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)))))
                .addComponent(license, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel12, jLabel13, jLabel2, jLabel3, jLabel5, jLabel6, jLabel8, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {EmailId, RoleJComboBox, city, contact, firstname, lastname, street, zipcode});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Browse, register});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(license, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(RoleJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(Browse))
                                .addGap(52, 52, 52)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(register))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(393, 393, 393)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(442, 442, 442)
                                .addComponent(jLabel10)))
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel11, jLabel12, jLabel13, jLabel2, jLabel3, jLabel5, jLabel6, jLabel8, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {EmailId, RoleJComboBox, city, contact, firstname, lastname, street, zipcode});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Browse, register});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailIdActionPerformed

    private void streetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetActionPerformed

    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
        
         JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new  File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images","jpg","png","jpeg");
        chooser.addChoosableFileFilter(filter);
        int result = chooser.showSaveDialog(null);
        if(result ==JFileChooser.APPROVE_OPTION){
            File f = chooser.getSelectedFile();

            try {
                origImage = ImageIO.read(f);

                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                ImageIO.write(origImage, "jpg", baos );
                baos.flush();
                immAsBytes = baos.toByteArray();
                baos.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            ImageIcon i= ResizeImage(f.getAbsolutePath(),null);
            license.setIcon(i);

        }else if (result == JFileChooser.CANCEL_OPTION){
            System.out.println("No File Selected");
    }                                        

    }//GEN-LAST:event_BrowseActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
     try{
        if(!(firstname.getText().equals("")) && !(lastname.getText().equals("")) && !(EmailId.getText().equals("")) && !(RoleJComboBox.getSelectedItem().equals("Select A Role")) && !(contact.getText().equals("")) && !(street.getText().equals("")) && !(city.getText().equals("")) && !(zipcode.getText().equals("")) && !(license.getIcon()== null)){
        String FN = firstname.getText();
        String LN = lastname.getText();
        String UN = EmailId.getText();
        String role = RoleJComboBox.getSelectedItem().toString();
        byte[] L = immAsBytes;
        String S = "Pending";
        String st = street.getText();
        String C = city.getText();
        double number = Double.parseDouble(contact.getText());
        int zip = Integer.parseInt(zipcode.getText());
        if(isValidEmailAddress(UN)){
            for(Network network:system.getNetworkList()){
            for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                    if(organization instanceof CustomerServiceOrganization){
                            organization.getCustomerDirectoy().createCustomer(FN, LN, UN, role, number, st, C, zip, L,S);
                }
                }       
            }
        }
        JOptionPane.showMessageDialog(null, "Thank You for Registering! \n We will get back as soon as the account is verified ");
        firstname.setText("");
        lastname.setText("");
        EmailId.setText("");
        RoleJComboBox.setSelectedItem("Select A Role");
        contact.setText("");
        street.setText("");
        city.setText("");
        zipcode.setText("");
        license.setText("");

        EmailId.setBackground(Color.white);
        }else{
            JOptionPane.showMessageDialog(null,"Please provide valid emailId");
        }
        }
        else{
              JOptionPane.showMessageDialog(null, "Please provide all the details along with the license");  
        }
     }catch (Exception e)
                    {
                     JOptionPane.showMessageDialog(null,"Please enter valid value for the fields");
                    }
    }//GEN-LAST:event_registerActionPerformed

    private void EmailIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailIdKeyReleased

        if(ismatched())
        {
            EmailId.setBackground(Color.GREEN);
            email.setText("");
        }
        else
        {
            EmailId.setBackground(Color.RED);
            email.setText("Not a Valid Email Address");
        }
    }//GEN-LAST:event_EmailIdKeyReleased
//public ImageIcon ResizeImage(String ImagePath){
//    ImageIcon MyImage =new ImageIcon(ImagePath);
//    Image img =MyImage.getImage();
//    Image newImg = img.getScaledInstance(license.getWidth(),license.getHeight(),Image.SCALE_SMOOTH);
//    ImageIcon image = new ImageIcon(newImg);
//    return image;
//}
public ImageIcon ResizeImage(String ImagePath,byte[] pic){
        ImageIcon MyImage =null;
        if(ImagePath!= null)
        {
         MyImage =new ImageIcon(ImagePath);   
        }
        
        else
        {
            MyImage =new ImageIcon(pic);  
        }
    
    Image img =MyImage.getImage();
    Image newImg = img.getScaledInstance(license.getWidth(),license.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
}
 public boolean ismatched() {
       if(isValidEmailAddress(EmailId.getText()))
       {
          return true;
                   } 
       else
       {
           return false;
       }
    }
 
 

public boolean isValidEmailAddress(String email) {
           String ePattern = "^(?!_)[a-zA-Z0-9_]+@(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,})$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(email);
           return m.matches();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Browse;
    private javax.swing.JTextField EmailId;
    private javax.swing.JComboBox RoleJComboBox;
    private javax.swing.JTextField city;
    private javax.swing.JTextField contact;
    private javax.swing.JLabel email;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastname;
    private javax.swing.JLabel license;
    private javax.swing.JButton register;
    private javax.swing.JTextField street;
    private javax.swing.JTextField zipcode;
    // End of variables declaration//GEN-END:variables
}
