/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OrderPlacement;

import Business.CustomerAccount.CustomerAccount;
import Business.EcoSystem;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author vaniv
 */
public class CustomerAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerAccountJPanel
     */
    private JPanel container;
    private EcoSystem system;
    private CustomerAccount account;
    private Organization organization;


    public CustomerAccountJPanel(JPanel Panel, EcoSystem system, CustomerAccount account, Organization organization) {
       initComponents();
       this.container =Panel;
       this.system =system;
       this.account =account;
       this.organization =organization;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personaldetails = new javax.swing.JButton();
        deliverydetailsbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 44, 91));

        personaldetails.setBackground(new java.awt.Color(44, 44, 91));
        personaldetails.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        personaldetails.setForeground(new java.awt.Color(171, 238, 255));
        personaldetails.setText("UPDATE PERSONAL DETAILS");
        personaldetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personaldetailsActionPerformed(evt);
            }
        });

        deliverydetailsbtn.setBackground(new java.awt.Color(44, 44, 91));
        deliverydetailsbtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        deliverydetailsbtn.setForeground(new java.awt.Color(171, 238, 255));
        deliverydetailsbtn.setText("UPDATE DELIVERY ADDRESS");
        deliverydetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverydetailsbtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(44, 44, 91));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(171, 238, 255));
        jButton1.setText("UPDATE USERNAME AND PASSWORD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(751, 751, 751)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliverydetailsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personaldetails, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(751, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deliverydetailsbtn, personaldetails});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addComponent(personaldetails)
                .addGap(48, 48, 48)
                .addComponent(deliverydetailsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {deliverydetailsbtn, personaldetails});

    }// </editor-fold>//GEN-END:initComponents

    private void deliverydetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverydetailsbtnActionPerformed
        container.removeAll();
        DeliveryDetailJPanel detail = new DeliveryDetailJPanel(container,system,account,organization);
        container.add(detail);
        CardLayout layout =(CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_deliverydetailsbtnActionPerformed

    private void personaldetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personaldetailsActionPerformed
        container.removeAll();
        PersonalDetailJPanel details = new PersonalDetailJPanel(container,system,account,organization);
        container.add(details);
        CardLayout layout =(CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_personaldetailsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       container.removeAll();
        UpdatePasswordJPanel details = new UpdatePasswordJPanel(container,system,account,organization);
        container.add(details);
        CardLayout layout =(CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deliverydetailsbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton personaldetails;
    // End of variables declaration//GEN-END:variables
}
