/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OrderPlacement;

import Buisness.Products.Product;
import Business.Cart.Cart;
import Business.CustomerAccount.CustomerAccount;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.Network.Network;
import Business.Order.Order;
import Business.Organization.Organization;
import Business.Organization.SupplierProcurementOrganization;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.CartJPanel;
import userinterface.LabRole.LabWorkAreaJPanel;

/**
 *
 * @author vaniv
 */
public class PaymentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaymentJPanel
     */
   private JPanel container;
   private EcoSystem system;
   private CustomerAccount account;
   private Enterprise enterprise;
   private Organization organization;
    public PaymentJPanel(JPanel container, EcoSystem system, CustomerAccount account,Organization organization, Enterprise enterprise) {
        initComponents();
        this.container =container;
         this.system= system;
         this.account = account;
         this.organization= organization;
         this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cardNumber = new javax.swing.JTextField();
        PaymentMethod = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        CVV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MonthJcomboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        YearComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        CardName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 44, 91));

        jPanel1.setBackground(new java.awt.Color(85, 79, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(171, 238, 255));
        jLabel2.setText("CARD NUMBER");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(171, 238, 255));
        jLabel3.setText("PAYMENT METHOD");

        cardNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        PaymentMethod.setBackground(new java.awt.Color(85, 79, 102));
        PaymentMethod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PaymentMethod.setForeground(new java.awt.Color(171, 238, 255));
        PaymentMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MASTERCARD", "VISA", "AMEX", "DISCOVER" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(171, 238, 255));
        jLabel4.setText("CVV");

        CVV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(171, 238, 255));
        jLabel5.setText("MONTH");

        MonthJcomboBox.setBackground(new java.awt.Color(85, 79, 102));
        MonthJcomboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MonthJcomboBox.setForeground(new java.awt.Color(171, 238, 255));
        MonthJcomboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(171, 238, 255));
        jLabel6.setText("YEAR");

        YearComboBox.setBackground(new java.awt.Color(85, 79, 102));
        YearComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        YearComboBox.setForeground(new java.awt.Color(171, 238, 255));
        YearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(171, 238, 255));
        jLabel7.setText("NAME");

        CardName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MonthJcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CardName, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(YearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(CVV, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(MonthJcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(YearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CardName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(171, 238, 255));
        jLabel1.setText("PAYMENT ");

        jButton1.setBackground(new java.awt.Color(44, 44, 91));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(171, 238, 255));
        jButton1.setText("MAKE PAYMENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 579, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(577, 577, 577))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(837, 837, 837)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(856, 856, 856)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addGap(110, 110, 110))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try{
        String Cardname = CardName.getText();
        int cvv = Integer.parseInt(CVV.getText());
        long CardNumber = Long.parseLong(cardNumber.getText());
        String Month =MonthJcomboBox.getSelectedItem().toString();
        int Year = Integer.parseInt(YearComboBox.getSelectedItem().toString());
        if (!(Cardname.equals("")) && !(CVV.getText().equals("")) && !(cardNumber.getText().equals("")) && !(Month.equals(""))){
        account.getCustomer().getPayment().setName(CardName.getText());
        account.getCustomer().getPayment().setCVV(Integer.parseInt(CVV.getText()));
        account.getCustomer().getPayment().setCardNumber(Long.parseLong(cardNumber.getText()));
        account.getCustomer().getPayment().setMonth(MonthJcomboBox.getSelectedItem().toString());
        account.getCustomer().getPayment().setYear(Integer.parseInt(YearComboBox.getSelectedItem().toString()));
        Order p = account.getOrderDirectory().createOrder(account.getCustomer().getFirstname());
        Organization o1 = null;
        Product prod = null;
        for(Cart cart:account.getCartDirectory().getCartList()){
            String name =cart.getName();
            int ID =cart.getProductID() ;
            String productType =cart.getProductType();
            double price = cart.getPrice();
            int quantity = cart.getQuantity();
            String supplierName = cart.getSupplierName();
            String Type = cart.getType();
            String Desc = cart.getDesc();
            String status="New";
     

            byte[] image=cart.getImagetry();
            p.createProduct(name, ID,Desc, price, quantity, Type, supplierName, productType,image,status);

            for(Product product:p.getProductList()){
            for(Network network:system.getNetworkList()){
            for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof SupplierEnterprise){
                        for(Organization o :e.getOrganizationDirectory().getOrganizationList()){
                        if(o instanceof SupplierProcurementOrganization){
                            o1 = o;
                                for(Product p1 : o.getProductDirectory().getAllProducts()){
                                    if (product.getName().equals(p1.getName())){
                                        p1.setQuantity(p1.getQuantity()-quantity);
//                                        if (p1.getQuantity() == 0){
//                                            o.getProductDirectory().deleteProduct(p1);
//                                        }
                                        prod = p1;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        }
        if(prod == null){
            JOptionPane.showMessageDialog(null,"Sorry for inconvenience\n The product is out of stock ");
            CartJPanel cart = new CartJPanel(container,system,account,organization,enterprise);
            container.add("confirmation",cart);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.next(container);
        }
        if( prod.getQuantity() == 0){
            o1.getProductDirectory().deleteProduct(prod);
            if(prod.getProductType().equals("Drug")){
                o1.getProductDirectory().deleteDrug(prod);
            }else if (prod.getProductType().equals("Vaccine")){
                o1.getProductDirectory().deleteVaccine(prod);
            }else if (prod.getProductType().equals("Equipment")){
                o1.getProductDirectory().deleteEquipment(prod);
        }
        }
        account.getCartDirectory().removeCartAll();
        container.removeAll();
        confirmationJPanel confirmation = new confirmationJPanel(container,system,account,p);
        container.add("confirmation",confirmation);
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
        }else{
            JOptionPane.showMessageDialog(null,"Please provide the values for every fields");
        }
        }
        catch (Exception e)
                    {
                     JOptionPane.showMessageDialog(null,"Please enter valid value for the fields");
                    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CVV;
    private javax.swing.JTextField CardName;
    private javax.swing.JComboBox MonthJcomboBox;
    private javax.swing.JComboBox PaymentMethod;
    private javax.swing.JComboBox YearComboBox;
    private javax.swing.JTextField cardNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
