/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OrderPlacement;

import Business.CustomerAccount.CustomerAccount;
import Business.EcoSystem;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author vaniv
 */
public class PersonalDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonalDetailJPanel
     */
    public PersonalDetailJPanel() {
        
    }
    private JPanel container;
    private EcoSystem system;
    private CustomerAccount account;
    private Organization organization;
    PersonalDetailJPanel(JPanel container, EcoSystem system, CustomerAccount account, Organization organization) {
        initComponents();
        this.container =container;
        this.system =system;
        this.account =account;
        this.organization =organization;
        firstname.setEnabled(false);
       lastname.setEnabled(false);
       contact.setEnabled(false);
       emailID.setEnabled(false);
       firstname.setText(account.getCustomer().getFirstname());
       lastname.setText(account.getCustomer().getLastname());
       contact.setText(String.valueOf(account.getCustomer().getContact()));
       emailID.setText(account.getCustomer().getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        emailID = new javax.swing.JTextField();
        EditBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();

        setBackground(new java.awt.Color(44, 44, 91));
        setForeground(new java.awt.Color(171, 238, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(171, 238, 255));
        jLabel1.setText("FIRST NAME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(171, 238, 255));
        jLabel2.setText("LAST NAME");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(171, 238, 255));
        jLabel3.setText("CONTACT");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(171, 238, 255));
        jLabel4.setText("EMAIL ID");

        firstname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lastname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        contact.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        emailID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailIDKeyReleased(evt);
            }
        });

        EditBtn.setBackground(new java.awt.Color(44, 44, 91));
        EditBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditBtn.setForeground(new java.awt.Color(171, 238, 255));
        EditBtn.setText("EDIT");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(44, 44, 91));
        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(171, 238, 255));
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        BackBtn.setBackground(new java.awt.Color(44, 44, 91));
        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(171, 238, 255));
        BackBtn.setText("BACK");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(171, 238, 255));
        jLabel5.setText("PERSONAL DETAILS");

        email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(171, 238, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(671, 671, 671)
                        .addComponent(BackBtn)
                        .addGap(124, 124, 124)
                        .addComponent(EditBtn)
                        .addGap(126, 126, 126)
                        .addComponent(updateBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(759, 759, 759)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contact)
                            .addComponent(lastname)
                            .addComponent(firstname)
                            .addComponent(emailID, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(850, 850, 850)
                        .addComponent(jLabel5)))
                .addContainerGap(377, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BackBtn, EditBtn, updateBtn});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {contact, emailID, firstname, jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, lastname});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
                            .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBtn)
                    .addComponent(EditBtn)
                    .addComponent(updateBtn))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {contact, emailID, firstname, jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, lastname});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BackBtn, EditBtn, updateBtn});

    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
    try{   
        String FN =firstname.getText();
        String LN = lastname.getText();
        Double Contact =Double.valueOf(contact.getText());
        String emailId =emailID.getText();
        if(!(FN.equals("")) && !((LN.equals(""))) && !((contact.getText().equals(""))) && !(emailId.equals("")) && isValidEmailAddress(emailId)){        
        account.getCustomer().setFirstname(firstname.getText());
       account.getCustomer().setLastname(lastname.getText());
       account.getCustomer().setContact(Double.valueOf(contact.getText()));
       account.getCustomer().setEmail(emailID.getText());
       firstname.setEnabled(false);
       lastname.setEnabled(false);
       contact.setEnabled(false);
       emailID.setEnabled(false);
       JOptionPane.showMessageDialog(null,"Personal Details Updated");}
        else{
            JOptionPane.showMessageDialog(null , " Please Enter all the fields");
        }
    }catch (Exception e)
                    {
                     JOptionPane.showMessageDialog(null,"Please enter valid value for the fields");
                    }
            
    }//GEN-LAST:event_updateBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
       firstname.setEnabled(true);
       lastname.setEnabled(true);
       contact.setEnabled(true);
       emailID.setEnabled(true);
    }//GEN-LAST:event_EditBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
       container.removeAll();
        CustomerAccountJPanel customer = new CustomerAccountJPanel(container,system,account,organization);
        container.add(customer);
        CardLayout layout =(CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void emailIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailIDKeyReleased
       if(ismatched())
        {
            emailID.setBackground(Color.GREEN);
            email.setText("");
        }
        else
        {
            emailID.setBackground(Color.RED);
            email.setText("Not a Valid Email Address");
        }
    }//GEN-LAST:event_emailIDKeyReleased

    public boolean ismatched() {
       if(isValidEmailAddress(emailID.getText()))
       {
          return true;
                   } 
       else
       {
           return false;
       }
    }
 
 

public boolean isValidEmailAddress(String email) {
           String ePattern = "^(?!_)[a-zA-Z0-9_]+@(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,})$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(email);
           return m.matches();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JTextField contact;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailID;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField lastname;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
