/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupOrderManagerRole;

import Buisness.Products.Product;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Order.Order;
import Business.Organization.CustomerProcurementOrganization;
import Business.Organization.Organization;
import Business.Organization.TpManagementOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BidWorkRequest;
import Business.WorkQueue.TpWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harshitha
 */
public class checkBiddingStatus extends javax.swing.JPanel {

    /**
     * Creates new form checkBiddingStatus
     */
      private UserAccount account;
    private Enterprise enterprise;
    private Organization organization;
    private JPanel userProcessContainer;
    private EcoSystem business;
    
    public checkBiddingStatus(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.account=account;
        this.enterprise=enterprise;
        this.organization=organization;
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        populateRequestTable();
       
        
    }
    
     public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) bidcond.getModel();
        
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(85,79,102));

        for (int i = 0; i < bidcond.getModel().getColumnCount(); i++) {
       bidcond.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
       }
        
        model.setRowCount(0);
         Organization org = null;
        for(Network network:business.getNetworkList()){
            for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization organization1:enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization1 instanceof CustomerProcurementOrganization){
                org = organization1;
                break;
            }
        }
            }
        }
        if (org!=null){
       // org.getWorkQueue().getWorkRequestList().clear();
        for (WorkRequest request : org.getWorkQueue().getWorkRequestList()){
            if(request.getStatus().equals("Approve"))
            {
                
            
            Object[] row = new Object[4];
            Product p=((BidWorkRequest) request).getPro();
            row[0] = p;
            row[1] = request.getStatus();
            Order o=((BidWorkRequest) request).getOrder();
            row[2]=o;
            model.addRow(row);
        }
            else 
            {
                DefaultTableModel model1 = (DefaultTableModel)rejectedTable.getModel();
        
                model1.setRowCount(0);
                 Object[] row = new Object[4];
            Product p=((BidWorkRequest) request).getPro();
            
            row[0] = p;
            row[1] = request.getStatus();
            Order o=((BidWorkRequest) request).getOrder();
            row[2]=o;
            model1.addRow(row);
          
                
            }
        }
   
     }   
        
     }
     
    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SupOrderManagerWorkAreaJPanel dwjp = (SupOrderManagerWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }                  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bidcond = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        msg = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        rejectedTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 44, 91));

        bidcond.setBackground(new java.awt.Color(44, 44, 91));
        bidcond.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bidcond.setForeground(new java.awt.Color(171, 238, 255));
        bidcond.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT", "STATUS", "ORDER"
            }
        ));
        bidcond.setSelectionBackground(new java.awt.Color(85, 79, 102));
        bidcond.setSelectionForeground(new java.awt.Color(171, 238, 255));
        jScrollPane1.setViewportView(bidcond);

        jButton2.setBackground(new java.awt.Color(44, 44, 91));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(171, 238, 255));
        jButton2.setText("SEND TO THIRDPATY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        msg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        rejectedTable.setBackground(new java.awt.Color(44, 44, 91));
        rejectedTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rejectedTable.setForeground(new java.awt.Color(171, 238, 255));
        rejectedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT", "STATUS", "ORDER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rejectedTable.setSelectionBackground(new java.awt.Color(85, 79, 102));
        rejectedTable.setSelectionForeground(new java.awt.Color(171, 238, 255));
        jScrollPane2.setViewportView(rejectedTable);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(171, 238, 255));
        jLabel1.setText("APPROVED ORDERS");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(171, 238, 255));
        jLabel2.setText("PENDING OR REJECTED ORDERS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(171, 238, 255));
        jLabel3.setText("ADD MESSAGE: ");

        jButton3.setBackground(new java.awt.Color(44, 44, 91));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(171, 238, 255));
        jButton3.setText("<< BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(510, 510, 510)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addGap(26, 26, 26)
                            .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(527, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(43, 43, 43))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jButton3});

    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = bidcond.getSelectedRow();
        if(selectedRow<0)
        {
             JOptionPane.showMessageDialog(null, "Please select a row from the table to send it to ThirdParty", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(msg.getText().equals(""))
        {
             JOptionPane.showMessageDialog(null, "Please enter a message to the ThirdParty");
        }
        else
        {
         

        if (selectedRow < 0){
            return;
        }
         Order o=(Order)bidcond.getValueAt(selectedRow, 2);
      //  String message = messageJTextField.getText();
        
         
      TpWorkRequest request = new TpWorkRequest();
      
     
       //
      Product p=(Product)bidcond.getValueAt(selectedRow, 0);
     //  p.setProStatus("Bided");
       request.setMessage(msg.getText());
      request.setProduct(p.getName());
        request.setSender(account);
        request.setStatus("SentFromSupplier");
       request.setOrder(o);
        
     Organization org = null;
        for(Network network:business.getNetworkList()){
            for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization organization1:enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization1 instanceof TpManagementOrganization){
                org = organization1;
                break;
            }
        }
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Order has been sent to ThirdParty");
            p.setStatus("Completed");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        BiddingSystem dwjp = (BiddingSystem) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
       
        
    


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bidcond;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField msg;
    private javax.swing.JTable rejectedTable;
    // End of variables declaration//GEN-END:variables
}

