/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdminRole;

import Business.Customer.Customer;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vaniv
 */
public class CustomerAdminRoleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerAdminRoleJPanel
     */
    private Organization organization;
    private Enterprise enterprise;
    private JPanel userProcessContainer;
    
    public CustomerAdminRoleJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        this.organization= organization;
        this.enterprise=enterprise;
        this.userProcessContainer =userProcessContainer;
                
        refreshTable();
          DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
         headerRenderer.setBackground(new Color(85,79,102));

         for (int i = 0; i < CustomerTable1.getModel().getColumnCount(); i++) {
        CustomerTable1.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
         for (int i = 0; i < DeniedTable.getModel().getColumnCount(); i++) {
        DeniedTable.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }

    public void refreshTable(){

      int rowCount = CustomerTable1.getRowCount();
            DefaultTableModel model = (DefaultTableModel)CustomerTable1.getModel();
        for(int i = rowCount - 1; i >=0; i--) {
            model.removeRow(i);
        }
      for(Customer c :organization.getCustomerDirectoy().getCustomerList()){
          Object row[] = new Object[4];
            row[0] =c;
            row[1]=c.getLastname();
            row[2]=c.getEmail();
            row[3]=c.getStatus();         
            model.addRow(row);
            
      }
      rowCount =CustomerTable1.getRowCount()-1;
            for(int j =0;j<=rowCount;j++){
                
             if((CustomerTable1.getValueAt(j, 3)).equals("Approved") || (CustomerTable1.getValueAt(j, 3)).equals("Denied")) {
                 model.removeRow(j);
                 rowCount= rowCount-1;
                 j--;
          } 
            }
            int rowCount1= DeniedTable.getRowCount();
            DefaultTableModel model1=(DefaultTableModel)DeniedTable.getModel();
            for(int m = rowCount1 - 1;m>=0;m--){
                model1.removeRow(m);
            }
            for(Customer c1:organization.getCustomerDirectoy().getCustomerList()){
                Object row[] = new Object[4];
                row[0] =c1;
                row[1]=c1.getLastname();
                row[2]=c1.getEmail();
                row[3]=c1.getStatus();
                model1.addRow(row);
            }
            rowCount1 = DeniedTable.getRowCount()-1;
            for(int k=0;k<=rowCount1;k++){
                if((DeniedTable.getValueAt(k, 3)).equals("Approved") || (DeniedTable.getValueAt(k, 3)).equals("Pending")){
                    model1.removeRow(k);
                    rowCount1 = rowCount1-1;
                    k--;
                }
            }
          }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeniedTable = new javax.swing.JTable();
        verify = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CustomerTable1 = new javax.swing.JTable();
        View = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(44, 44, 91));

        DeniedTable.setBackground(new java.awt.Color(44, 44, 91));
        DeniedTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeniedTable.setForeground(new java.awt.Color(171, 238, 255));
        DeniedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "User Name", "Status"
            }
        ));
        jScrollPane1.setViewportView(DeniedTable);

        verify.setBackground(new java.awt.Color(44, 44, 91));
        verify.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        verify.setForeground(new java.awt.Color(171, 238, 255));
        verify.setText("VERIFY");
        verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(44, 44, 91));
        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(171, 238, 255));
        back.setText("BACK");

        CustomerTable1.setBackground(new java.awt.Color(44, 44, 91));
        CustomerTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CustomerTable1.setForeground(new java.awt.Color(171, 238, 255));
        CustomerTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "User Name", "Status"
            }
        ));
        jScrollPane2.setViewportView(CustomerTable1);

        View.setBackground(new java.awt.Color(44, 44, 91));
        View.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        View.setForeground(new java.awt.Color(171, 238, 255));
        View.setText("VIEW DENIED");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(510, 510, 510)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(back)
                        .addGap(466, 466, 466)
                        .addComponent(verify))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(View)
                        .addGap(351, 351, 351)))
                .addContainerGap(519, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {View, back, verify});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(verify))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(View)
                .addGap(114, 114, 114))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {View, back, verify});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyActionPerformed
        int selectRow= CustomerTable1.getSelectedRow();
        if(selectRow<0)
        {
            JOptionPane.showMessageDialog(null, "Please select customer to verify");
        }
        else
        {
            Customer f=(Customer)CustomerTable1.getValueAt(selectRow, 0);

            UpdateJPanel updateCustomer= new UpdateJPanel(userProcessContainer,f,organization);
            userProcessContainer.add("updateCustomer",updateCustomer);
            CardLayout layout=(CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_verifyActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        int selectRow= DeniedTable.getSelectedRow();
        if(selectRow<0)
        {
            JOptionPane.showMessageDialog(null, "Please select customer to verify");
        }
        else
        {
            Customer f=(Customer)DeniedTable.getValueAt(selectRow, 0);

            UpdateJPanel updateCustomer= new UpdateJPanel(userProcessContainer,f,organization);
            userProcessContainer.add("updateCustomer",updateCustomer);
            CardLayout layout=(CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_ViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CustomerTable1;
    private javax.swing.JTable DeniedTable;
    private javax.swing.JButton View;
    private javax.swing.JButton back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton verify;
    // End of variables declaration//GEN-END:variables
}
