/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdminRole;

import Business.Customer.Customer;
import Business.Organization.Organization;
import Business.Role.Role;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.SuppliesManagerRole.ViewPanel;

/**
 *
 * @author vaniv
 */
public class UpdateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
   private JPanel userProcessContainer;
   private Customer f;
   private Organization organization;
    UpdateJPanel(JPanel userProcessContainer, Customer f, Organization organization) {
        initComponents();
        this.userProcessContainer =userProcessContainer;
         this.f=f;
         this.organization =organization;
         firstname.setText(f.getFirstname());
         lastname.setText(f.getLastname());
         EmailId.setText(f.getEmail());
         Role.setText(f.getRole());
         Statusjcombobox.setSelectedItem(f.getStatus());
         firstname.setEditable(false);
         lastname.setEditable(false);
         EmailId.setEditable(false);
         Role.setEditable(false);
//         ImageIcon image =new ImageIcon((Image) f.getLicense());
//         license.setIcon(f.getLicense());
         populateRoleComboBox(organization);
         BufferedImage imgFromDb = null;
        InputStream in = new ByteArrayInputStream(f.getImagetry());
        try {
             imgFromDb = ImageIO.read(in);
               
    ImageIcon icon = new ImageIcon(imgFromDb);
   //ImageIcon i = ResizeImage(imgFromDb,null);
         license.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(ViewPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }
    
    public ImageIcon ResizeImage(String ImagePath,byte[] pic){
        ImageIcon MyImage =null;
        if(ImagePath!= null)
        {
         MyImage =new ImageIcon(ImagePath);   
        }
        
        else
        {
            MyImage =new ImageIcon(pic);  
        }
    
    Image img =MyImage.getImage();
    Image newImg = img.getScaledInstance(license.getWidth(),license.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
}
    private void populateRoleComboBox(Organization organization){
        rolejcombobox.removeAllItems();
        for (Role role : organization.getSupportedRole()){
            rolejcombobox.addItem(role);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        license = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        EmailId = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        Statusjcombobox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        rolejcombobox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        username1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Role = new javax.swing.JTextField();
        PasswordField1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(44, 44, 91));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(171, 238, 255));
        jLabel1.setText("FIRST NAME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(171, 238, 255));
        jLabel2.setText("LAST NAME");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(171, 238, 255));
        jLabel3.setText("EMAIL ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(171, 238, 255));
        jLabel4.setText("STATUS");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(171, 238, 255));
        jLabel5.setText("LICENSE");

        license.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(171, 238, 255));
        jLabel6.setText("SET ROLE");

        firstname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        EmailId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lastname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Statusjcombobox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Statusjcombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pending", "Approved", "Denied", " " }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(171, 238, 255));
        jLabel7.setText("ROLE");

        rolejcombobox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rolejcombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(171, 238, 255));
        jLabel8.setText("USER NAME");

        username1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(171, 238, 255));
        jLabel9.setText("PASSWORD");

        jButton1.setBackground(new java.awt.Color(44, 44, 91));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(171, 238, 255));
        jButton1.setText("VERIFY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(44, 44, 91));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(171, 238, 255));
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(171, 238, 255));
        jLabel10.setText("ROLE");

        Role.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        PasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(44, 44, 91));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(171, 238, 255));
        jButton3.setText("GENERATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(license, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstname)
                                    .addComponent(lastname)
                                    .addComponent(EmailId)
                                    .addComponent(Role)
                                    .addComponent(Statusjcombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rolejcombobox, 0, 180, Short.MAX_VALUE)
                                    .addComponent(username1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(PasswordField1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButton1)
                                .addGap(26, 26, 26)
                                .addComponent(jButton2)))))
                .addContainerGap(832, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel2, jLabel3, jLabel4, jLabel5, jLabel7, jLabel8, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {EmailId, PasswordField1, Role, Statusjcombobox, firstname, lastname, rolejcombobox, username1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(license, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Statusjcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addComponent(jLabel6)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rolejcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(username1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(2, 2, 2)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel2, jLabel3, jLabel4, jLabel5, jLabel7, jLabel8, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {EmailId, PasswordField1, Role, Statusjcombobox, firstname, lastname, rolejcombobox, username1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2067, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        f.setStatus((String) Statusjcombobox.getSelectedItem());

        if(f.getStatus() == "Denied" || f.getStatus() == "Pending"){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure with the status??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
            userProcessContainer.remove(this);
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
            Component[] components= userProcessContainer.getComponents();
            for (Component c: components)
            {

                if(c instanceof CustomerAdminRoleJPanel)

                {
                    CustomerAdminRoleJPanel panel=(CustomerAdminRoleJPanel)c;
                    panel. refreshTable();
                }
            }
        }                
        }
        if (f.getStatus() == "Approved"){
           try{
            Role role = (Role) rolejcombobox.getSelectedItem();
            String username = username1.getText();
            String password2 = PasswordField1.getPassword().toString();
            if(!(username.equals("")) && !(password2.equals(""))){
            organization.getCustomerAccountDirectory().createUserAccount(username, password2, f, role);
            String emailId=f.getEmail();
            JavaApplication14 em=new JavaApplication14(emailId,username,password2);
            userProcessContainer.remove(this);
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
            Component[] components= userProcessContainer.getComponents();
            for (Component c: components)
            {

                if(c instanceof CustomerAdminRoleJPanel)

                {
                    CustomerAdminRoleJPanel panel=(CustomerAdminRoleJPanel)c;
                    panel. refreshTable();
                }
            }
          }else{
                JOptionPane.showMessageDialog(null,"Please generate the username and password");
            }      
        }catch (Exception e)
                    {
                     JOptionPane.showMessageDialog(null,"Please enter valid value for the fields");
                    }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        Component[] components= userProcessContainer.getComponents();
        for (Component c: components)
        {

            if(c instanceof CustomerAdminRoleJPanel)

            {
                CustomerAdminRoleJPanel panel=(CustomerAdminRoleJPanel)c;
                panel. refreshTable();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        username1.setText(generate_Username(10).toString());
        PasswordField1.setText(generate_Password(8).toString());
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField1ActionPerformed

static char[] generate_Username(int leng) 
    { 
       
  
        // Generating a username which includes uppercase, lowercase, numeric values and special characters
  
        String Uppercase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"; 
        String Lowercase = "abcdefghijklmnopqrstuvwxyz"; 
        String numbers = "0123456789"; 
        String symbols = "!_."; 
  
        String values = Uppercase + Lowercase + numbers+symbols; 
                      
        Random random_method = new Random(); 
  
        char[] username = new char[leng]; 
  
        for (int i = 0; i < leng; i++) 
        { 
            
            username[i] = values.charAt(random_method.nextInt(values.length())); 
  
        } 
        return username; 
    } 

static char[] generate_Password(int leng) 
    { 
       
  
        // Generating a password which includes uppercase, lowercase and numeric values
  
        String Uppercase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"; 
        String Lowercase = "abcdefghijklmnopqrstuvwxyz"; 
        String numbers = "0123456789"; 
        //String symbols = "!_."; 
  
        String values = Uppercase + Lowercase + numbers; 
                      
        Random random_method = new Random(); 
  
        char[] password = new char[leng]; 
  
        for (int i = 0; i < leng; i++) 
        { 
            
            password[i] = values.charAt(random_method.nextInt(values.length())); 
  
        } 
        return password; 
    } 

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailId;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JTextField Role;
    private javax.swing.JComboBox Statusjcombobox;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastname;
    private javax.swing.JLabel license;
    private javax.swing.JComboBox rolejcombobox;
    private javax.swing.JTextField username1;
    // End of variables declaration//GEN-END:variables
}
